name: Build GKI - Release

on:
  workflow_dispatch:
  push:
    branches: ["rebase"]
  pull_request:
    branches: ["rebase"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TIME: ${{ steps.set-time.outputs.TIME }}
    steps:
      - name: Get current time
        id: set-time
        run: echo "TIME=$(date +'%Y%m%d')" >> $GITHUB_ENV && echo "TIME=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Free disk space
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq curl
          curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          submodules: "true"
          fetch-depth: 1
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 8
      - name: Setup build environment
        run: |
          # Install require dependencies
          sudo apt update -y
          sudo apt install bc binutils-dev bison build-essential ccache curl flex git libelf-dev lld make python3-dev cpio python-is-python3 tar perl wget lz4 unzip -y
          git clone https://github.com/bachnxuan/AnyKernel3.git AnyKernel3
          cd AnyKernel3 && rm -rf .git .github && cd ..
          # Initialize KernelSU-Next submodule
          git submodule update --init --recursive
          cd KernelSU-Next
          git fetch --unshallow origin next-susfs-dev:next-susfs-dev
          git checkout next-susfs-dev
          git pull origin next-susfs-dev
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 7.5G
      - name: Download toolchain
        working-directory: ./..
        run: |
          AOSP_MIRROR=https://android.googlesource.com
          BRANCH=main-kernel-build-2024
          git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
          git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1 mkbootimg
          mkdir clang-tc && cd clang-tc
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-12.0.0_r12/clang-r416183b1.tar.gz
          tar -xvzf clang-r416183b1.tar.gz
          rm -rf clang-r416183b1.tar.gz
      - name: Set boot sign key
        env:
          BOOT_SIGN_KEY: ${{ secrets.BOOT_SIGN_KEY }}
        run: |
          if [ ! -z "$BOOT_SIGN_KEY" ]; then
            echo "$BOOT_SIGN_KEY" > ../kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem
          else
            echo "BOOT_SIGN_KEY is not set. Exiting..."
            exit 1
          fi
      - name: Build
        run: |
          bash build.sh
      - name: Making ak3 zip
        run: |
          mv ./out/arch/arm64/boot/Image.gz $GITHUB_WORKSPACE
          cd AnyKernel3
          ZIP_NAME="android12-5.10.X-lts-${{ env.TIME }}-AnyKernel3.zip"
          echo "Creating zip file: $ZIP_NAME..."
          cp ../Image.gz ./Image.gz
          zip -r "../$ZIP_NAME" ./*
          rm ./Image.gz
      - name: Initialize environment for building boot image
        run: |
          echo "BOOT_SIGN_KEY_PATH=$GITHUB_WORKSPACE/../kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem" >> $GITHUB_ENV
          echo "AVBTOOL=$GITHUB_WORKSPACE/../kernel-build-tools/linux-x86/bin/avbtool" >> $GITHUB_ENV
          echo "MKBOOTIMG=$GITHUB_WORKSPACE/../mkbootimg/mkbootimg.py" >> $GITHUB_ENV
          echo "UNPACK_BOOTIMG=$GITHUB_WORKSPACE/../mkbootimg/unpack_bootimg.py" >> $GITHUB_ENV
      - name: Build boot image
        run: |
          mkdir bootimgs && cd bootimgs

          GKI_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-2025-02_r1.zip
          FALLBACK_URL=https://dl.google.com/android/gki/gki-certified-boot-android12-5.10-2023-01_r1.zip

          echo "Checking if GKI kernel URL is reachable: $GKI_URL"
          status=$(curl -sL -w "%{http_code}" "$GKI_URL" -o /dev/null)

          if [ "$status" = "200" ]; then
              echo "[+] Downloading from GKI_URL"
              curl -Lo gki-kernel.zip "$GKI_URL"
          else
              echo "[+] $GKI_URL not found, using $FALLBACK_URL"
              curl -Lo gki-kernel.zip "$FALLBACK_URL"
          fi

          echo "Unzipping the downloaded kernel..."
          unzip gki-kernel.zip && rm gki-kernel.zip

          echo "Unpacking boot.img..."
          FULL_PATH=$(pwd)/boot-5.10.img
          echo "Unpacking using: $FULL_PATH"

          echo "Running unpack_bootimg.py..."
          $UNPACK_BOOTIMG --boot_img="$FULL_PATH"

          echo "Building boot.img"
          ls -la
          cp ../Image.gz ./Image.gz
          $MKBOOTIMG --header_version 4 --kernel Image.gz --output boot.img --ramdisk out/ramdisk --os_version 12.0.0 --os_patch_level 2025-02
          $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY_PATH       
          cp ./boot.img ../android12-5.10.X-lts-${{ env.TIME }}-boot.img
      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: kernel
          path: |
            ./android12-5.10.X-lts-${{ env.TIME }}-AnyKernel3.zip
            ./android12-5.10.X-lts-${{ env.TIME }}-boot.img
